export const SET_NAME = 'SET_NAME';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';
export const SET_CONNECTION_PROFILE = 'SET_CONNECTION_PROFILE';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';
export const ADD_MESSAGE = 'ADD_MESSAGE';