export const SET_NAME = 'SET_NAME';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';
export const SET_BASIC_PROFILE = 'SET_BASIC_PROFILE';
export const SET_ADVANCED_PROFILE = 'SET_ADVANCED_PROFILE';